#include "../include/Profil.h"
#include "../include/Partie.h"
#include "../include/Personnage.h"
#include "../include/Record.h"
#include "../include/Menu.h"

#include <stdlib.h>
#include <stdio.h>
#include <SDL/SDL.h>
#include <SDL/SDL_ttf.h>
#include <SDL/SDL_image.h>

int main(int argc, char *argv[])
{
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_TIMER) == -1) // Démarrage de la SDL. Si erreur :
    {
        fprintf(stderr, "Erreur d'initialisation de la SDL : %s\n", SDL_GetError()); // Écriture de l'erreur
        exit(EXIT_FAILURE); // On quitte le programme
    }

    if(TTF_Init() == -1)
	{
	    fprintf(stderr, "Erreur d'initialisation de TTF_Init : %s\n", TTF_GetError());
	    exit(EXIT_FAILURE);
	}

    /*FILE *fichier;

    fichier = fopen("profil/profil.base", "wb");

    unsigned int nb = 1;
    char nom[21] = {'M', 'i', 'c', 'h', 'e', 'l'};

    fwrite(&nb, sizeof(unsigned int), 1, fichier);
    fwrite(&nb, sizeof(unsigned int), 1, fichier);
    fwrite(nom, sizeof(char)*21, 1, fichier);*/

    SDL_Surface *ecran = NULL;

    ecran = SDL_SetVideoMode(800, 600, 32, SDL_HWSURFACE|SDL_DOUBLEBUF);
    SDL_WM_SetCaption("Digger", NULL);
    SDL_WM_SetIcon(IMG_Load("img/perso.png"), NULL);

    Menu *menu = NULL;

/* NIVEAU 3
    FILE *fichier = fopen("niveau/3.niveau", "wb");
    Bloc grille[18][25] = {
    	{FRUIT, FRUIT, ROCHER, ROCHER, ROCHER, ROCHER, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, MUR, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER},
    	{FRUIT, ROCHER, ROCHER, ROCHER, ROCHER, HERBE, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, MUR, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT},
    	{ROCHER, ROCHER, ROCHER, ROCHER, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, MUR, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER},
    	{ROCHER, ROCHER, ROCHER, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, MUR, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER},
    	{ROCHER, ROCHER, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, MUR, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER},
    	{ROCHER, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, MUR, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER},
    	{HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, MUR, MUR, MUR, MUR, MUR, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE},
    	{HERBE, HERBE, HERBE, HERBE, HERBE, MUR, MUR, MUR, MUR, ROCHER, ROCHER, ROCHER, MUR, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE},
    	{HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, MUR, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, MUR, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE},
    	{HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, MUR, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE},
    	{ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, MUR, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE},
    	{ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, MUR, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER},
    	{ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, MUR, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER,ROCHER, ROCHER},
    	{MUR, MUR, HERBE, HERBE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, HERBE, HERBE, MUR, MUR},
    	{HERBE, HERBE, HERBE, HERBE, HERBE, HERBE,HERBE,HERBE, HERBE, HERBE, MUR, HERBE, HERBE, HERBE, MUR, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE},
    	{HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, MUR, HERBE, PERSO, HERBE, MUR, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE},
    	{HERBE, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, HERBE, HERBE, HERBE, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, HERBE},
    	{FRUIT,FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT}
    };

    unsigned int index=3;
    fwrite(grille, sizeof(Bloc)*18*25,1,fichier);
    fwrite(&index,sizeof(unsigned int),1,fichier);

*/



    /* NIVEAU 2
    FILE *fichier = fopen("niveau/2.niveau", "wb");
    Bloc grille[18][25] = {
    	{FRUIT, FRUIT, ROCHER, ROCHER, ROCHER, ROCHER, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, MUR, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT},
    	{FRUIT, ROCHER, ROCHER, ROCHER, ROCHER, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, MUR, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER},
    	{ROCHER, ROCHER, ROCHER, ROCHER, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, MUR, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER},
    	{ROCHER, ROCHER, ROCHER, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, MUR, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER},
    	{ROCHER, ROCHER, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, MUR, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER},
    	{ROCHER, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, MUR, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE},
    	{HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, MUR, MUR, MUR, MUR, MUR, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE},
    	{HERBE, HERBE, HERBE, HERBE, HERBE, MUR, MUR, MUR, MUR, ROCHER, ROCHER, ROCHER, MUR, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE},
    	{HERBE, HERBE, HERBE, HERBE, HERBE, MUR, ROCHER, FRUIT, ROCHER, FRUIT, ROCHER, ROCHER, MUR, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE},
    	{HERBE, ROCHER, ROCHER, ROCHER, HERBE, MUR, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE},
    	{HERBE, ROCHER, ROCHER, ROCHER, HERBE, HERBE, FRUIT, FRUIT, ROCHER, ROCHER, FRUIT, FRUIT, MUR, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER},
    	{HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, FRUIT, FRUIT, ROCHER, ROCHER, FRUIT, FRUIT, MUR, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER},
    	{HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, MUR, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER,ROCHER, ROCHER},
    	{MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, HERBE, HERBE, MUR, MUR},
    	{HERBE, HERBE, HERBE, FRUIT, FRUIT, FRUIT,FRUIT,HERBE, HERBE, HERBE, MUR, HERBE, HERBE, HERBE, MUR, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE},
    	{HERBE, HERBE, HERBE, ROCHER, ROCHER, ROCHER, ROCHER, HERBE, HERBE, HERBE, MUR, HERBE, PERSO, HERBE, MUR, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE, HERBE},
    	{FRUIT, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, HERBE, HERBE, HERBE, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, ROCHER, FRUIT},
    	{FRUIT,FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT, FRUIT}
    };

    unsigned int index=2;
    fwrite(grille, sizeof(Bloc)*18*25,1,fichier);
    fwrite(&index,sizeof(unsigned int),1,fichier);

    */


    menu = Menu_initialiser();

    Menu_ajouterOption(menu, JOUER);
    Menu_ajouterOption(menu, OPTIONS);
    Menu_ajouterOption(menu, QUITTER);

    Menu_derouler(menu, ecran);


    Menu_liberer(menu);
    TTF_Quit();
    SDL_Quit();

    return 0;
}
